version: '3.8'
services:
  postgres_database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=newsfindme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "9000:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  newsfindme-api_container:
    container_name: newsfindme_backend
    build: 
      context: .
    depends_on:
      - postgres_database
    ports: 
      - "3000:3000"
    networks:
      - app-network
    environment:
      - SERVER_PORT=$SERVER_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=postgres_database
      - POSTGRES_USER=$POSTGRES_USER
      - WEB_SCRAPPER_URL=web_scraper_container:80
    volumes:
      - .:/home/node/newsfindme-api
      - node_modules:/home/node/newsfindme-api/node_modules
    command: npm run dev
    
  web_scraper_container:
    container_name: scraper
    build:
      context: ./web-scraper/.
    networks:
      - app-network
    volumes:
      - ./web-scraper/:/app
    ports:
      - 56733:80
    
 
volumes:
  db-data:
    driver: local 
  node_modules:
  scraper_app:
  
networks:
  app-network:
    driver: bridge